---
- name: Manage travis | Gather information about the .travis.yml file
  ansible.builtin.stat:
    path: "{{ __fule_role_path }}/.travis.yml"
  register: __fule_stat_travis_yml

- name: Manage travis | Handle the existing .travis.yml file.
  when:
    - __fule_stat_travis_yml.stat.exists
    - __fule_stat_travis_yml.stat.checksum is defined
    - __fule_stat_travis_yml.stat.checksum in fule_travis_checksum
  block:

    - name: Manage travis | Update default .travis.yml file
      ansible.builtin.template:
        dest: "{{ __fule_role_path }}/.travis.yml"
        src: travis.yml.j2
        mode: '0644'
      when:
        - fule_update_default_travis_file

    - name: Manage travis | Remove default .travis.yml file
      ansible.builtin.file:
        path: "{{ __fule_role_path }}/.travis.yml"
        state: absent
      register: __fule_travis_removed
      failed_when: not __fule_travis_removed.changed
      when:
        - fule_remove_default_travis_file
