---
# Config tasks for this role
- name: Config | Build supported platform variable.
  ansible.builtin.set_fact:
    __fule_role_platforms: |
      {% set supported_platforms = {} -%}
      {% for current_platform in fule_molecule_platforms -%}
      {%   if supported_platforms[current_platform['name']] is defined %}
      {%     set _ = supported_platforms[current_platform['name']].append(current_platform['release']) -%}
      {%   else -%}
      {%     set _ = supported_platforms.__setitem__(current_platform['name'], [current_platform['release']]) -%}
      {%   endif -%}
      {% endfor -%}
      {{ supported_platforms }}

- name: Config | Include add_molecule_structure tasks.
  ansible.builtin.include_tasks:
    file: molecule/add_molecule_structure.yml

- name: Config | Execute changes on role structure.
  ansible.builtin.include_tasks:
    file: ./role/update_tasks.yml
  when: fule_modify_role_structure

- name: Config | Update role meta information.
  ansible.builtin.template:
    dest: "{{ __fule_role_path }}/meta/main.yml"
    src: "meta/main.yml.j2"
    mode: '0655'
  vars:
    fule_role_meta_platforms: "{{ __fule_role_platforms }}"
  when: fule_replace_meta_file

- name: Config | Update README.md file.
  ansible.builtin.include_tasks:
    file: ./role/update_readme.md.yml
  when: fule_update_default_readme_file

- name: Config | Handle the .travis.yml file.
  ansible.builtin.include_tasks:
    file: ./role/manage_travis_file.yml
  when: fule_update_default_travis_file
    or fule_remove_default_travis_file

- name: Config | Handle .yamllint.yml file.
  ansible.builtin.include_tasks:
    file: ./role/manage_yamllint.yml
  when: fule_manage_yamllint_configuration_file
