---
- name: Install | Build up installation command
  ansible.builtin.set_fact:
    _ag_parameters: "{{ _ag_parameters | default('') ~ ' --' ~ item['parameter'] ~ ' ' ~ item['value'] }}"
  loop:
    - parameter: role-skeleton
      value: "{{ fule_role_skeleton }}"
      condition: "fule_role_skeleton | length > 0"
    - parameter: "init-path"
      value: "{{ fule_working_dir }}"
  when: "{{ item['condition'] | default(true) }}"

# Install tasks for this roles
- name: Install | Create the role with molecule
  ansible.builtin.command:
    cmd: "ansible-galaxy role init {{ _ag_parameters }} {{ fule_role_name }}"
    chdir: "{{ fule_working_dir }}"
    creates: "{{ fule_working_dir }}/{{ fule_role_name }}"

- name: Install | Set variable with role_path
  ansible.builtin.set_fact:
    __fule_role_path: "{{ fule_working_dir }}/{{ fule_role_name }}"
