---
- name: Main | Include assertion file
  ansible.builtin.include_tasks:
    file: 'requirements.yml'

- name: Main | Run variable gathering in ad-hoc plays
  when: ansible_play_name == "Ansible Ad-Hoc"
  ansible.builtin.setup:

- name: Main | Include variable files
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - files:
        - "{{ lookup('ansible.builtin.env', 'HOME') }}/.ansible/fule.conf.yml"
        - "{{ lookup('ansible.builtin.env', 'HOME') }}/.ansible/fule.cnf.yml"
        - "{{ lookup('ansible.builtin.env', 'HOME') }}/.ansible/fule/variables.yml"
        - "{{ lookup('ansible.builtin.env', 'HOME') }}/.ansible/fule.yml"
        - "{{ lookup('ansible.builtin.env', 'HOME') }}/.ansible/fule.cnf"
      skip: true

- name: Main | Include install tasks
  ansible.builtin.include_tasks: install.yml
- name: Main | Include config tasks
  ansible.builtin.include_tasks: config.yml
- name: Main | Include service tasks
  ansible.builtin.include_tasks: service.yml
...
