---
- name: Converge
  hosts: all
  tasks:

    - name: "Molecule structure | Include variable file"
      ansible.builtin.include_vars: variables.yml

    - name: "Molecule structure | Include spreadcat.fule"
      ansible.builtin.include_role:
        name: "spreadcat.fule"
