---
- name: Readme | Converge
  hosts: all
  tasks:

    - name: "Molecule readme | Include variable file"
      ansible.builtin.include_vars: variables.yml

    - name: "Molecule readme | Include spreadcat.fule"
      ansible.builtin.include_role:
        name: "spreadcat.fule"
