---
- name: Lintable | Converge
  hosts: all
  tasks:

    - name: "Molecule lintable | Include variable file"
      ansible.builtin.include_vars: variables.yml

    - name: "Molecule lintable | Include spreadcat.fule"
      ansible.builtin.include_role:
        name: "spreadcat.fule"
