---
- name: Gitlabcicd | Prepare
  hosts: all
  gather_facts: false
  tasks:

    - name: Prepare | Include variables
      ansible.builtin.include_vars: variables.yml

    - name: Prepare | Deploy a custom cicd file
      ansible.builtin.copy:
        dest: /home/ansible/custom-ci.yml
        content: |
          ---
          # Custom CI file
