---
- name: Converge
  hosts: all
  tasks:

    - name: "Molecule default | Include variable file"
      ansible.builtin.include_vars: variables.yml

    - name: "Molecule default | Include dbv.folecule"
      ansible.builtin.include_role:
        name: "dbv.folecule"
