---
# Variables for this scenario
fule_role_name: dbv.testrole
fule_role_author: Ola Nordmann
fule_working_dir: /tmp
fule_username: ansible
fule_group: ansible

specs: &specs
  tmpfs: ['/run', '/tmp']
  volumes: ['/sys/fs/cgroup:/sys/fs/cgroup:ro']
  capabilities: ['SYS_ADMIN']
  command: '/lib/systemd/systemd'
  pre_build_image: true

fule_molecule_platforms:
  - name: Fedora
    release: 37
    image: localhost/fedora37-ansible-nonroot
    provisioner:
      hostvars:
        ansible_user: ansible
    specs:
      <<: *specs
  - name: Ubuntu
    release: 22.04
    image: localhost/ubuntu2204-ansible-nonroot
    provisioner:
      hostvars:
        ansible_user: ansible
    specs:
      <<: *specs

fule_manage_changelog_file: true
