---
# Ansible playbook for verification.
- name: Default | Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify | Load the roles default variables
      ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Verify | Assert the files from the skeleton role exist
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        line: "# Role skeleton"
        state: present
      check_mode: true
      register: __file_status
      failed_when: __file_status['changed']
      loop:
        - /tmp/dbv.testrole/tasks/install.yml
        - /tmp/dbv.testrole/tasks/config.yml
        - /tmp/dbv.testrole/tasks/service.yml
        - /tmp/dbv.testrole/tasks/main.yml
        - /tmp/dbv.testrole/meta/main.yml
